Abstract selector method injectable test
SteampunkFoundry/at4dx-1 pull request #2
Opened 2021-03-19 15:20 UTC by bspeelm

2021-03-21 20:46 UTC, ImJohnMDaniel requested changes

2021-03-21 20:46 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-selector-method-injection/AbstractSelectorMethodInjectableTest.cls
> +    public class Parameters
@bspeelm -- Normally, the convention will be simply the class name of `Parameters` since it would be a 2nd tier inner class within the SelectorMethod class.  So, this is more of a comment than anything else.  If we were to have mulitple "parameters" classes, then I would request a more unique naming.

Having said all of that, I am requesting that the class be changed to `private` so that it could not accidentally be referenced outside of this test class.

Please let me know if you have questions.

cc: @ctchipps, @madiraza, and @BrandonFeather

2021-03-21 20:46 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/framework-selector-method-injection/AbstractSelectorMethodInjectableTest.cls
> +            }
@bspeelm, if you would not mind, please adjust and correct the indention throughout this and other classes but also specifically here.  Please ensure that you use "four spaces" and not a tab character for indention.  thanks!

2021-03-22 14:40 UTC, bspeelm commented on sfdx-source/core/test/classes/framework-selector-method-injection/AbstractSelectorMethodInjectableTest.cls
> +    private class SelectByNameSelectorTestMethod
Done, Thank you for the info on the naming convention here.

2021-03-22 14:40 UTC, bspeelm commented on sfdx-source/core/test/classes/framework-selector-method-injection/AbstractSelectorMethodInjectableTest.cls
> +            )getParams();
Done

2021-03-22 14:40 UTC, bspeelm commented on sfdx-source/core/test/classes/framework-selector-method-injection/AbstractSelectorMethodInjectableTest.cls
> +                    Account.Name+ ' in :nameSet').toSOQL()
Done

2021-03-22 14:41 UTC, bspeelm commented on sfdx-source/core/test/classes/framework-selector-method-injection/AbstractSelectorMethodInjectableTest.cls
> +    public class Parameters
Thank you for the info. Makes sense to have it as private.

2021-03-22 14:42 UTC, bspeelm commented on sfdx-source/core/test/classes/framework-selector-method-injection/AbstractSelectorMethodInjectableTest.cls
> +            }
Fixed

2021-03-22 17:33 UTC, ImJohnMDaniel approved these changes

2021-03-22 17:33 UTC, merged

2021-03-22 17:34 UTC, ImJohnMDaniel commented
Looks good @bspeelm!