Application S Object Unit of Work Test
SteampunkFoundry/at4dx-1 pull request #3
Opened 2021-03-19 20:33 UTC by bspeelm

2021-03-22 20:14 UTC, ImJohnMDaniel requested changes

2021-03-22 20:14 UTC, ImJohnMDaniel commented on sfdx-source/core/test/classes/Utility/TestDataFactory.cls
> +    	    acctList.add(new Account(Name='TestAccount'+i));
@bspeelm, please utilize the [fflib_IDGenerator](https://github.com/apex-enterprise-patterns/fflib-apex-mocks/blob/master/sfdx-source/apex-mocks/main/classes/fflib_IDGenerator.cls) class found in the [AEP ApexMocks project](https://github.com/apex-enterprise-patterns/fflib-apex-mocks/).

When you are setting up mock records that will not be stored in the database, the `fflib_IDGenerator` is a great way to generate SObject-correct IDs.

2021-03-22 23:04 UTC, bspeelm commented on sfdx-source/core/test/classes/Utility/TestDataFactory.cls
> +    public static List<Account> getAccList(Integer numAccts){
Done

2021-03-22 23:22 UTC, bspeelm commented on sfdx-source/core/test/classes/Utility/TestDataFactory.cls
> +        return singleAccount;
Done

2021-03-22 23:22 UTC, bspeelm commented on sfdx-source/core/test/classes/Utility/TestDataFactory.cls
> +    public static List<Account> getAccList(Integer numAccts){
Done

2021-03-22 23:25 UTC, bspeelm commented on sfdx-source/core/test/classes/Utility/TestDataFactory.cls
> +    	    acctList.add(new Account(Name='TestAccount'+i));
I left as is for now. For many of the tests the Account needs to be able to be inserted or registered and committed. Now it may be that the tests themselves need to be reconfigured but I will wait for your notes to make this change as it broke the tests to create the account record id's with  fflib_IDGenerator.

2021-03-26 20:29 UTC, ImJohnMDaniel approved these changes

2021-03-26 20:29 UTC, merged